=== sanketfall2014/HTML-XML-and-XSD/books.xsd
<?xml version='1.0' encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
    <xs:element name='bookdata'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name='book' minOccurs='1' maxOccurs='unbounded'>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name='author_info'>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name='author_name' type='Authorname'/>
                                        <xs:element name='date_of_birth'>
                                            <xs:simpleType>
                                                <xs:restriction base='xs:date'>
                                                    <xs:minInclusive value='1970-01-01'/>
                                                    <xs:maxInclusive value='2000-12-31'/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name='highedu'>
                                            <xs:simpleType>
                                                <xs:restriction base='xs:string'>
                                                    <xs:pattern value='MS|BS|BA|PHD'/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name='address' type='Address1'/>
                                        <xs:element name='Pbookno'>
                                            <xs:simpleType>
                                                <xs:restriction base='xs:integer'>
                                                    <xs:minInclusive value='1'/>
                                                    <xs:maxExclusive value='100'/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name='Coname' type='xs:string' minOccurs='0' maxOccurs='unbounded'/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name='bookinfo' type='Book_info'/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name='Authorname'>
        <xs:sequence>
            <xs:element name='Firstname'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:pattern value='[A-Z][a-zA-z]*'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name='Lastname'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:pattern value='[A-Z][a-zA-z]*'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name='Address1'>
        <xs:sequence>
            <xs:element name='StreetnameAuthor'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:whiteSpace value='collapse'/>
                        <xs:pattern value='[0-9]*[ ]?[a-zA-z]*'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name='Aptnum' minOccurs='0' maxOccurs='1'>
                <xs:simpleType>
                    <xs:restriction base='xs:integer'>
                        <xs:minExclusive value='100'/>
                        <xs:maxInclusive value='1000'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name='CityAuthor'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:pattern value='[A-Z][a-zA-z]*'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name='zipcodeAuthor' type='xs:integer'/>
            <xs:element name='CountryAuthor'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:pattern value='[A-Z]*'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name='Book_info'>
        <xs:sequence>
            <xs:element name='Title'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:pattern value='[A-Z][a-zA-z]*[ ]?[A-Z][a-zA-z]*'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name='ISBN'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:pattern value='[A-Za-z0-9]{3}-[A-Za-z0-9]{3}-[A-Za-z0-9]{4}'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="price">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:decimal">
                            <xs:attribute name="currency" type="currencyType"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name='Pub_date' type='xs:date'/>
            <xs:element name='Pub_info' type='pubinfo'/>

        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="currencyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="pounds"/>
            <xs:enumeration value="euros"/>
            <xs:enumeration value="dollars"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name='pubinfo'>
        <xs:sequence>
            <xs:element name='pub_name'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:pattern value='[A-Z][a-zA-z]*[ ]?[A-Z][a-zA-z]*'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name='pub_address' type='pubaddress'/>
            <xs:element name='C_time'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:pattern value='[0-9]*-[0-9]*-[0-9]*'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name='pubaddress'>
        <xs:sequence>
            <xs:element name='Streetname'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:whiteSpace value='collapse'/>
                        <xs:pattern value='[0-9]*[ ]?[a-zA-z]*'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name='suite_no' type='xs:integer' minOccurs='0' maxOccurs='1'/>
            <xs:element name='City'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:pattern value='[A-Z][a-zA-z]*'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name='zipcode' type='xs:integer'/>
            <xs:element name='Country'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:pattern value='[A-Z]*'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== sanketfall2014/HTML-XML-and-XSD/books.xml
<?xml version='1.0'?>
<bookdata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
    <book>
        <author_info>
            <author_name>
                <Firstname>Chirag</Firstname>
				<Middlename>B</Middlename>
                <Lastname>Chudasama</Lastname>
            </author_name>
            <date_of_birth>1992-03-06</date_of_birth>
            <highedu>MS</highedu>
            <address>
                <StreetnameAuthor>7815 McCallum</StreetnameAuthor>
                <Aptnum>6202</Aptnum>
                <CityAuthor>Dallas</CityAuthor>
                <zipcodeAuthor>75252</zipcodeAuthor>
                <CountryAuthor>USA</CountryAuthor>
            </address>
            <Pbookno>3</Pbookno>
        </author_info>
		<Pub_info>
                <pub_name>The Bookhouse</pub_name>
                <pub_address>
                    <Streetname>1818 Vepari road</Streetname>
                    <suite_no>26</suite_no>
                    <City>Chennai</City>
                    <zipcode>50001</zipcode>
                    <Country>India</Country>
                </pub_address>
                <C_time>06-04-11</C_time>
            </Pub_info>
        <bookinfo>
            <Title>The Secret</Title>
            <ISBN>976-973-4473</ISBN>
            <price currency="dollars">124.00</price>
            <Pub_date>2008-06-19</Pub_date>
        </bookinfo>
    </book>
    <book>
        <author_info>
            <author_name>
                <Firstname>Kaushik</Firstname>
                <Lastname>Desai</Lastname>
            </author_name>
            <date_of_birth>1992-07-28</date_of_birth>
            <highedu>PHD</highedu>
            <address>
                <StreetnameAuthor>202 GreenView</StreetnameAuthor>
                <CityAuthor>Mumbai</CityAuthor>
                <zipcodeAuthor>400059</zipcodeAuthor>
                <CountryAuthor>India</CountryAuthor>
            </address>
            <Pbookno>1</Pbookno>
        </author_info>
        <bookinfo>
            <Title>Harry Potter</Title>
            <ISBN>469-422-4218</ISBN>
            <price currency="dollars">65.00</price>
            <Pub_date>2013-02-28</Pub_date>
            <Pub_info>
                <pub_name>Techmax Publications</pub_name>
                <pub_address>
                    <Streetname>52 Varacha road</Streetname>
                    <suite_no>420</suite_no>
                    <City>Surat</City>
                    <zipcode>700015</zipcode>
                    <Country>India</Country>
                </pub_address>
                <C_time>02-10-01</C_time>
            </Pub_info>
        </bookinfo>
    </book>
    <book>
        <author_info>
            <author_name>
                <Firstname>Sanket</Firstname>
                <Lastname>Prabhu</Lastname>
            </author_name>
            <date_of_birth>1988-05-10</date_of_birth>
            <highedu>MBA</highedu>
            <address>
                <StreetnameAuthor>215 Dickson st</StreetnameAuthor>
                <CityAuthor>London</CityAuthor>
                <zipcodeAuthor>85080</zipcodeAuthor>
                <CountryAuthor>UK</CountryAuthor>
            </address>
            <Pbookno>5</Pbookno>
        </author_info>
        <bookinfo>
            <Title>Human Computer Interaction</Title>
            <ISBN>808-024-2854</ISBN>
            <price currency="dollars">93.00</price>
            <Pub_date>2005-10-21</Pub_date>
            <Pub_info>
                <pub_name>Square Space</pub_name>
                <pub_address>
                    <Streetname>77th Brooklyn ave</Streetname>
                    <suite_no>22</suite_no>
                    <City>New York</City>
                    <zipcode>72015</zipcode>
                    <Country>USA</Country>
                </pub_address>
                <C_time>09-02-09</C_time>
            </Pub_info>
        </bookinfo>
    </book>
	
	
	
	<book>
        <author_info>
            <author_name>
                <Firstname>Arjun</Firstname>
                <Lastname>Gohil</Lastname>
            </author_name>
            <date_of_birth>1982-09-15</date_of_birth>
            <highedu>BS</highedu>
            <address>
                <StreetnameAuthor>2525 Anand Nagar</StreetnameAuthor>
                <Aptnum>2</Aptnum>
                <CityAuthor>Mumbai</CityAuthor>
                <zipcodeAuthor>400068</zipcodeAuthor>
                <CountryAuthor>India</CountryAuthor>
            </address>
            <Pbookno>9</Pbookno>
        </author_info>
        <bookinfo>
            <Title>Awesome Accounting!</Title>
            <ISBN>989-620-2569</ISBN>
            <price currency="dollars">66.00</price>
            <Pub_date>2000-05-25</Pub_date>
            <Pub_info>
                <pub_name>Lynda Inc</pub_name>
                <pub_address>
                    <Streetname>798 Coit rd</Streetname>
                    <suite_no>65</suite_no>
                    <City>Dallas</City>
                    <zipcode>70581</zipcode>
                    <Country>USA</Country>
                </pub_address>
                <C_time>14-05-06</C_time>
            </Pub_info>
        </bookinfo>
    </book>
	
	
	
	<book>
        <author_info>
            <author_name>
                <Firstname>Nilesh</Firstname>
                <Lastname>Pandey</Lastname>
            </author_name>
            <date_of_birth>1985-03-28</date_of_birth>
            <highedu>MS</highedu>
            <address>
                <StreetnameAuthor>65 Jamaica st</StreetnameAuthor>
                <Aptnum>13</Aptnum>
                <CityAuthor>Sydney</CityAuthor>
                <zipcodeAuthor>12457</zipcodeAuthor>
                <CountryAuthor>USA</CountryAuthor>
            </address>
            <Pbookno>4</Pbookno>
        </author_info>
        <bookinfo>
            <Title>Trending Tyres</Title>
            <ISBN>902-283-5363</ISBN>
            <price currency="dollars">111.00</price>
            <Pub_date>2007-11-09</Pub_date>
            <Pub_info>
                <pub_name>Pocketnow Solutions</pub_name>
                <pub_address>
                    <Streetname>A7a Royal ave</Streetname>
                    <suite_no>05</suite_no>
                    <City>Delhi</City>
                    <zipcode>60021</zipcode>
                    <Country>India</Country>
                </pub_address>
                <C_time>07-02-21</C_time>
            </Pub_info>
        </bookinfo>
    </book>
	
	
</bookdata>
